# Generated by Django 6.0.7 on 2026-09-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vault", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keybackup",
            name="updated_date",
            field=models.DateField(null=True),
        ),
    ]
